- name: Time
  hosts: all
  become: true
  handlers:
  - name: Restart systemd-timedated
    service:
      name: systemd-timedated
      state: restarted
  tasks:
  - name: Set timezone
    shell: timedatectl set-timezone UTC
    notify: Restart systemd-timedated
  - name: Enable NTP
    shell: timedatectl set-ntp true
    notify: Restart systemd-timedated
  - name: Get status
    shell: timedatectl status
    register: timedatectl_status
