- name: Time
  hosts: all
  sudo: true
  handlers:
  - name: restart openntpd
    service: name=openntpd state=restarted
  - name: update tzdata
    command: dpkg-reconfigure --frontend noninteractive tzdata
  tasks:
  - set_fact:
      openntpd_conf: /etc/ntpd.conf
    when: ansible_distribution == 'FreeBSD'
  - set_fact:
      openntpd_conf: /etc/openntpd//ntpd.conf
    when: ansible_distribution == 'Debian'

  - name: Copy UTC timezone (FreeBSD)
    copy: src=/usr/share/zoneinfo/UTC dest=/etc/localtime
    when: ansible_distribution == 'FreeBSD'
  - name: Copy UTC timezone (Debian)
    template: dest=/etc/timezone src=templates/timezone
    when: ansible_distribution == 'Debian'
    notify: update tzdata

  - name: Install openntpd
    apt: name=openntpd state=latest
    when: ansible_distribution == 'Debian'
    notify: restart openntpd
  - name: Install openntpd (FreeBSD)
    pkgng: name=openntpd state=present
    when: ansible_distribution == 'FreeBSD'
    notify: restart openntpd

  - name: Enable openntpd (FreeBSD)
    when: ansible_distribution == 'FreeBSD'
    notify: restart openntpd
    lineinfile: dest=/etc/rc.conf regexp=^openntpd_enable= line=openntpd_enable=YES
  - name: Set openntpd flags (Debian)
    when: ansible_distribution == 'Debian'
    notify: restart openntpd
    lineinfile: dest=/etc/default/openntpd regexp=^DAEMON_OPTS= line='DAEMON_OPTS="-svf /etc/openntpd/ntpd.conf"'
  - name: Set openntpd flags (FreeBSD)
    when: ansible_distribution == 'FreeBSD'
    notify: restart openntpd
    lineinfile: dest=/etc/rc.conf regexp=^openntpd_flags= line=openntpd_flags=-sv

  - name: Paste openntpd config
    template: src=templates/ntpd.conf dest={{ openntpd_conf }}
    notify: restart openntpd
